<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<Authors>Rene Peuser</Authors>
		<Company>Rene Peuser Softwaresolutions</Company>
		<Product>DotNetTool.Service</Product>
		<PackageLicenseFile>license.txt</PackageLicenseFile>
		<Copyright>Copyright 2020 (c) Rene Peuser. All rights reserved.</Copyright>
		<PackageProjectUrl>https://renepeuser.visualstudio.com/DotNetTool.Service</PackageProjectUrl>
		<RepositoryUrl>https://renepeuser.visualstudio.com/DotNetTool.Service</RepositoryUrl>
		<PackageReleaseNotes>Fix process starts command which hangs in some situations</PackageReleaseNotes>
		<Description>Use 'dotnet tool' as service in your .net projects. The commands are wrapped so you can handle very comfortable the commands of the 'dotnet tool' cli as a service.</Description>
		<PackageTags>C#;DotNet;CLI;dotenet tool;dotnet tool as as service;DNTAAS;</PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="ArgumentCheck\" />
		<Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\license.txt" Pack="true" PackagePath="license.txt" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
	</ItemGroup>

</Project>
